version: "3.8"

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 8180:3000
    volumes:
      - ./src:/usr/src/app/src
      - ./prisma:/usr/src/app/prisma
    env_file: .env
    networks:
      - dockerNet
    depends_on:
      # - queue
      - db
  # queue:
  #   image: rabbitmq:3.13.0-rc.2-management
  #   ports:
  #     - 8181:5672
  #     - 8182:15672
  #   environment:
  #     RABBITMQ_DEFAULT_USER: test-user
  #     RABBITMQ_DEFAULT_PASS: test-user
  #   networks:
  #     - dockerNet
  db:
    image: postgres:latest
    ports:
      - 8183:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Aa123456
      POSTGRES_DB: wbd_db_rest
    networks:
      - dockerNet
networks:
  dockerNet:
    external:
      true