version: "3.8"

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 8180:3000
    networks:
      - dockerNet
    depends_on:
      - queue
      - db
  queue:
    image: rabbitmq:3.13.0-rc.2-management
    ports:
      - 8181:5672
    networks:
      - dockerNet
  db:
    image: postgres:latest
    ports:
      - 8182:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Aa123456
      POSTGRES_DB: wbd_db_rest
    networks:
      - dockerNet
networks:
  dockerNet:
    external:
      true