version: "3.8"

services:
  app:
    container_name: booking-app
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 8180:3000
    volumes:
      - ./src:/usr/src/app/src
    env_file: .env
    networks:
      - dockerNet
    depends_on:
      - queue
      - db
  db:
    container_name: booking-db
    image: postgres:latest
    ports:
      - 8181:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Aa123456
      POSTGRES_DB: bookingdb
    networks:
      - dockerNet
    volumes:
      - ./db:/docker-entrypoint-initdb.d
  queue:
    container_name: central-queue
    image: rabbitmq:3.13.0-rc.2-management
    ports:
      - 8200:5672
      - 8201:15672
    environment:
      RABBITMQ_DEFAULT_USER: test-user
      RABBITMQ_DEFAULT_PASS: test-user
    volumes:
      - ./rabbitmq:/var/lib/rabbitmq
    networks:
      - dockerNet

networks:
  dockerNet:
    external:
      true