version: '3.8'
services:
  api:
    ports:
      - "8082:8080"
    env_file: .env_docker
    volumes:
      - .:/usr/src/app
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    networks:
      - dockerNet
  db:
    image: mysql:latest
    ports:
      - "8182:3306"
    env_file: .env_docker
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - ./db:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d
    networks:
      - dockerNet
networks:
  dockerNet:
    external:
      true
